version: '3.9'

services:
  # Gateway
  gateway:
    build: ./gateway
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
      - user-service
    environment:
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 1h



  # AUTH SERVICE STACK
  auth-db:
    image: postgres:16-alpine
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5433:5432"
    volumes:
      - auth_pgdata:/var/lib/postgresql/data

  migrate-auth:
    image: postgres:16-alpine
    depends_on:
      - auth-db
    volumes:
      - ./auth-service/migrations:/migrations
    entrypoint: >
      sh -c "
        echo '⏳ Waiting for auth-db...' &&
        sleep 3 &&
        psql postgresql://auth_user:auth_pass@auth-db:5432/auth_db -f /migrations/001_init.sql
      "

  auth-service:
    build: ./auth-service
    depends_on:
      - auth-db
      - migrate-auth
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      PRO_POSTGRESQL_USER: auth_user
      PRO_POSTGRESQL_PASS: auth_pass
      PRO_POSTGRESQL_HOST: auth-db
      PRO_POSTGRESQL_PORT: 5432
      PRO_POSTGRESQL_NAME: auth_db
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 1h

  # USER SERVICE STACK
  user-db:
    image: postgres:16-alpine
    container_name: user_db
    restart: always
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    ports:
      - "5434:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  migrate-user:
    image: postgres:16-alpine
    working_dir: /app
    depends_on:
      - user-db
    volumes:
      - ./user-service/migrations:/migrations
    entrypoint: >
      sh -c "
        echo '⏳ Waiting for user-db...' &&
        sleep 3 &&
        psql postgresql://user_user:user_pass@user-db:5432/user_db -f /migrations/001_init.sql
      "

  user-service:
    build: ./user-service
    depends_on:
      - user-db
      - migrate-user
    ports:
      - '3002:3002'
    environment:
      NODE_ENV: development
      PORT: 3002
      PRO_POSTGRESQL_USER: user_user
      PRO_POSTGRESQL_PASS: user_pass
      PRO_POSTGRESQL_HOST: user-db
      PRO_POSTGRESQL_PORT: 5432
      PRO_POSTGRESQL_NAME: user_db
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 1h

volumes:
  auth_pgdata:
    driver: local
  user_pgdata:
    driver: local
  