openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /appointments:
    post:
      summary: Create appointment
      responses:
        '201':
          description: Created
    get:
      summary: List appointments
      responses:
        '200':
          description: OK
  /appointments/{id}:
    get:
      summary: Get appointment
      responses:
        '200':
          description: OK
    put:
      summary: Update appointment
      responses:
        '200':
          description: OK
