apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: chiropractor
  labels:
    app: blog-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
        tier: backend
    spec:
      containers:
      - name: blog-service
        image: your-ecr-repo/chiropractor-blog-service:latest
        ports:
        - containerPort: 3003
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: BLOG_SERVICE_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chiropractor-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: JWT_EXPIRES_IN
        - name: PRO_MONGODB_HOST
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MONGO_HOST
        - name: PRO_MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: BLOG_MONGO_PORT
        - name: PRO_MONGODB_NAME
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: BLOG_MONGO_NAME
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: LOG_LEVEL
        - name: RATE_LIMIT_WINDOW_MS
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: RATE_LIMIT_WINDOW_MS
        - name: RATE_LIMIT_MAX_REQUESTS
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: RATE_LIMIT_MAX_REQUESTS
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: chiropractor
  labels:
    app: blog-service
spec:
  selector:
    app: blog-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
    name: http
  type: ClusterIP 