apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: chiropractor
  labels:
    app: gateway
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        tier: frontend
    spec:
      containers:
      - name: gateway
        image: your-ecr-repo/chiropractor-gateway:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: GATEWAY_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: NODE_ENV
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chiropractor-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: JWT_EXPIRES_IN
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: CORS_ORIGIN
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: chiropractor-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: chiropractor
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
  type: LoadBalancer 