apiVersion: v1
kind: PersistentVolume
metadata:
  name: chiropractor-logs-pv
  labels:
    type: local
    app: chiropractor
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/chiropractor-logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chiropractor-logs-pvc
  namespace: chiropractor
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chiropractor-uploads-pv
  labels:
    type: local
    app: chiropractor
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/chiropractor-uploads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chiropractor-uploads-pvc
  namespace: chiropractor
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi 