openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /messages:
    $ref: '#/components/schemas/Deprecated'
  /api/conversations:
    post:
      summary: Open conversation
      responses:
        '200':
          description: OK
    get:
      summary: List conversations
      responses:
        '200':
          description: OK
  /api/conversations/{id}/messages:
    get:
      summary: Conversation history
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
