openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /register:
    post:
      summary: Register a user
      responses:
        '201':
          description: Created
  /login:
    post:
      summary: Login
      responses:
        '200':
          description: OK
