openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /register:
    post:
      summary: Register a user
      responses:
        '201':
          description: Created
  /login:
    post:
      summary: Login and receive JWT
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  statusCode:
                    type: integer
                  message:
                    type: string
                  metadata:
                    type: object
                    properties:
                      token:
                        type: string
  /verify:
    post:
      summary: Verify JWT token
      responses:
        '200':
          description: OK
