openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /profiles:
    post:
      summary: Create profile
      responses:
        '201':
          description: Created
  /profiles/{id}:
    get:
      summary: Get profile
      responses:
        '200':
          description: OK
    put:
      summary: Update profile
      responses:
        '200':
          description: OK
  /recovery:
    post:
      summary: Create recovery record
      responses:
        '201':
          description: Created
    get:
      summary: List recovery records
      responses:
        '200':
          description: OK
  /recovery/{id}:
    get:
      summary: Get recovery record
      responses:
        '200':
          description: OK
    put:
      summary: Update recovery record
      responses:
        '200':
          description: OK
    delete:
      summary: Delete recovery record
      responses:
        '200':
          description: OK
  /work-impact:
    post:
      summary: Create work impact record
      responses:
        '201':
          description: Created
    get:
      summary: List work impact records
      responses:
        '200':
          description: OK
  /work-impact/{id}:
    get:
      summary: Get work impact record
      responses:
        '200':
          description: OK
    put:
      summary: Update work impact record
      responses:
        '200':
          description: OK
    delete:
      summary: Delete work impact record
      responses:
        '200':
          description: OK
  /details-descriptions:
    post:
      summary: Create details description
      responses:
        '201':
          description: Created
    get:
      summary: Get details description
      responses:
        '200':
          description: OK
    put:
      summary: Update details description
      responses:
        '200':
          description: OK
    delete:
      summary: Delete details description
      responses:
        '200':
          description: OK

  /pain-descriptions:
    post:
      summary: Create pain description
      responses:
        '201':
          description: Created
    get:
      summary: List pain descriptions
      responses:
        '200':
          description: OK
  /pain-descriptions/{id}:
    get:
      summary: Get pain description
      responses:
        '200':
          description: OK
    put:
      summary: Update pain description
      responses:
        '200':
          description: OK
    delete:
      summary: Delete pain description
      responses:
        '200':
          description: OK
  /health-conditions:
    post:
      summary: Create health condition record
      responses:
        '201':
          description: Created
    get:
      summary: List health condition records
      responses:
        '200':
          description: OK
  /health-conditions/{id}:
    get:
      summary: Get health condition record
      responses:
        '200':
          description: OK
    put:
      summary: Update health condition record
      responses:
        '200':
          description: OK
    delete:
      summary: Delete health condition record
      responses:
        '200':
          description: OK
  /patient-intake:
    post:
      summary: Create patient intake
      responses:
        '201':
          description: Created
    get:
      summary: List patient intake records
      responses:
        '200':
          description: OK
  /patient-intake/{id}:
    get:
      summary: Get patient intake
      responses:
        '200':
          description: OK
    put:
      summary: Update patient intake
      responses:
        '200':
          description: OK
    delete:
      summary: Delete patient intake
      responses:
        '200':
          description: OK
