openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /profiles:
    post:
      summary: Create profile
      responses:
        '201':
          description: Created
  /profiles/{id}:
    get:
      summary: Get profile
      responses:
        '200':
          description: OK
    put:
      summary: Update profile
      responses:
        '200':
          description: OK
  /report-groups:
    post:
      summary: Create report group
      responses:
        '201':
          description: Created
  /report-groups/{id}:
    get:
      summary: Get report group
      responses:
        '200':
          description: OK
    put:
      summary: Update report group
      responses:
        '200':
          description: OK
    delete:
      summary: Delete report group
      responses:
        '200':
          description: OK
  /report-groups/{id}/recovery:
    post:
      summary: Create recovery record
      responses:
        '201':
          description: Created
    get:
      summary: Get recovery record
      responses:
        '200':
          description: OK
    put:
      summary: Update recovery record
      responses:
        '200':
          description: OK
    delete:
      summary: Delete recovery record
      responses:
        '200':
          description: OK
  /report-groups/{id}/work-impact:
    post:
      summary: Create work impact record
      responses:
        '201':
          description: Created
    get:
      summary: Get work impact record
      responses:
        '200':
          description: OK
    put:
      summary: Update work impact record
      responses:
        '200':
          description: OK
    delete:
      summary: Delete work impact record
      responses:
        '200':
          description: OK
